# Generated by Django 5.0.4 on 2024-04-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audioguideapp", "0048_alter_user_propic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="city",
            new_name="citys",
        ),
    ]
